default:
  context:
      class: 'FeatureContext'    
      parameters:  
        wd_host: 'http://127.0.0.1:4444/wd/hub'
        wd_capabilities: { "browser": "firefox"}
  paths:
   features: %behat.paths.base%/../features/
   bootstrap: %behat.paths.base%/../features/bootstrap      